--require("core.plugin_config.gruvbox")
require("core.plugin_config.vscode")
require("core.plugin_config.ufo")
require("core.plugin_config.autocmp")
require("core.plugin_config.tabs")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.lsp")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")

